import { useState, useEffect } from "react";
import { type NextPage } from "next";
import Head from "next/head";
import { FächerTimeLine } from "~/components/fächer/FächerTimeline";


import { api } from "~/utils/api";
import { type Tstunde } from "~/server/api/routers/db";

const Home: NextPage = () => {
  const [weekNo, setWeekNo] = useState(getWeekNo());
	const [weekData, setWeekData] = useState<Tstunde[]>()

  function getWeekNo() {
    const today = new Date();
    const year = new Date(today.getFullYear(), 0, 1);
    const days = Math.floor((today.valueOf() - year.valueOf()) / (24 * 60 * 60 * 1000));
    const week = Math.ceil((today.getDay() + 1 + days) / 7);
    return week;
  }

  const woche = api.db.kw.useQuery({ gruppe: 40, kw: weekNo });
	useEffect(() => {
		const w = woche.data?.result
		setWeekData(w)
	}, [woche])
	

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Woche {weekNo - 8} (kw{weekNo})
        </h1>
        {woche.error ? woche.error.message : ""}
        {weekData ? (
          <FächerTimeLine data={weekData} currentWeek={weekNo == getWeekNo()} />
        ) : (
          <p>Loading tRPC query...</p>
        )}
      </main>
    </>
  );
};

export default Home;
