import { useState, useEffect } from "react";
import { type NextPage } from "next";
import Head from "next/head";
import { Select } from "@mantine/core";
import { TimelineTabs } from "~/components/TimelineTabs";

const Home: NextPage = () => {
    const [selectedGroup, setSelectedGroup] = useState<number>(40);

    function getWeekNo() {
        const today = new Date();
        const year = new Date(today.getFullYear(), 0, 1);
        const days = Math.floor(
            (today.valueOf() - year.valueOf()) / (24 * 60 * 60 * 1000)
        );
        const week = Math.ceil((today.getDay() - 1 + days) / 7);
        return week;
    }

    const selectGroup = (groupString: string) => {
        const groupNo = parseInt(groupString);
        if (window) window.localStorage.setItem("gruppe", groupNo.toString());
        setSelectedGroup(groupNo);
    };

    useEffect(() => {
        const localGroupNo = window.localStorage.getItem("gruppe");
        if (localGroupNo) setSelectedGroup(parseInt(localGroupNo));
    }, []);

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <div className="flex items-center justify-between pr-4">
                    <h1>
                        Woche {getWeekNo() - 8} (KW {getWeekNo()})
                    </h1>
                    <Select
                        className="w-36"
                        value={selectedGroup.toString()}
                        onChange={selectGroup}
                        data={[
                            { value: "40", label: "Gruppe 20/40" },
                            { value: "41", label: "Gruppe 20/41" },
                            { value: "42", label: "Gruppe 20/42" },
                        ]}
                    />
                </div>
                <TimelineTabs group={selectedGroup} currentWeek={getWeekNo()} />
            </>
        </>
    );
};

export default Home;
